Retrievers:
  - source_name: ZendeskSource
    type: ZendeskTickets
    enabled: false
    params:
      credentials:
        email:
        token:
        subdomain:

    custom_fields:
    excempt_fields:

    post_retrieval_actions:
      - function: anonymize_emails
        apply_to_all: true
        blacklisted_patterns:
          - "@acme.com"
        blacklisted_fields:
          - id
        # fields:
        #   - field 1
        #   - field 2

  - source_name: ArticleSource
    type: ZendeskArticles
    enabled: true
    params:
      subdomain:
      locale: en-us
      credentials:
        username:
        password:

    post_retrieval_actions:
      - function: anonymize_emails
        apply_to_all: true
        blacklisted_patterns:
          - "@acme.com"
        blacklisted_fields:
          - id

  - source_name: JiraSource
    type: Jira
    enabled: true
    params:
      credentials:
        username:
        password:
        url:
      projects:
        - Project1

    post_retrieval_actions:
      - function: anonymize_emails
        apply_to_all: true
        blacklisted_patterns:
          - "@acme.com"
        blacklisted_fields:
          - id

Target:
  host:
  dbname:
  user:
  password:
